-- =============================================
-- ARTICLES TIZIMI
-- =============================================

-- 1. Articles jadvali
CREATE TABLE IF NOT EXISTS articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  level TEXT NOT NULL CHECK (level IN ('A1','A2','B1','B2','C1','C2')),
  topic TEXT NOT NULL,
  image_url TEXT,
  read_time_minutes INTEGER DEFAULT 3,
  word_count INTEGER DEFAULT 300,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Article savollar jadvali
CREATE TABLE IF NOT EXISTS article_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_answer TEXT NOT NULL CHECK (correct_answer IN ('A','B','C','D')),
  order_num INTEGER DEFAULT 1
);

-- 3. Foydalanuvchi progressi
CREATE TABLE IF NOT EXISTS article_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT false,
  test_score INTEGER,
  test_total INTEGER,
  completed_at TIMESTAMPTZ,
  UNIQUE(user_id, article_id)
);

-- RLS
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "articles_public_read" ON articles FOR SELECT USING (true);
CREATE POLICY "article_questions_public_read" ON article_questions FOR SELECT USING (true);
CREATE POLICY "article_progress_user" ON article_progress FOR ALL USING (auth.uid() = user_id);

-- =============================================
-- 100 TA ARTICLE SEED DATA
-- =============================================

INSERT INTO articles (title, content, level, topic, read_time_minutes, word_count) VALUES

-- A1 LEVEL (20 ta)
('My Daily Routine', 'Every day I wake up at 7 o''clock in the morning. First, I wash my face and brush my teeth. Then I eat breakfast. I usually have bread, eggs, and tea for breakfast. After breakfast, I go to school. School starts at 8 o''clock. I study English, Math, and Science at school. I have lunch at 12 o''clock. After school, I come home and do my homework. In the evening, I watch TV or read books. I go to bed at 10 o''clock at night. I like my daily routine because it keeps me organized.', 'A1', 'Daily Life', 3, 120),

('My Family', 'I have a small family. There are four people in my family. My father''s name is John. He is a teacher. My mother''s name is Mary. She is a doctor. I have one sister. Her name is Lisa. She is eight years old. I am ten years old. We live in a small house. Our house has three rooms. We have a garden with flowers. I love my family very much. We are happy together.', 'A1', 'Family', 2, 100),

('My Favorite Food', 'I love eating food. My favorite food is pizza. Pizza has bread, cheese, and tomato sauce. I also like hamburgers and french fries. For breakfast, I eat eggs and toast. I drink orange juice in the morning. For lunch, I have soup and salad. I do not like vegetables very much. But I know vegetables are healthy. My favorite fruit is apple. Apples are red and sweet. I eat one apple every day. Food gives us energy to work and play.', 'A1', 'Food', 2, 110),

('Animals in the Zoo', 'I visited the zoo last Sunday. The zoo has many animals. I saw lions, tigers, and elephants. Lions are big and have yellow fur. Tigers have orange and black stripes. Elephants are the biggest animals in the zoo. They have long noses called trunks. I also saw monkeys. Monkeys are funny animals. They climb trees and eat bananas. My favorite animal is the giraffe. Giraffes have very long necks. They eat leaves from tall trees. The zoo was very exciting.', 'A1', 'Animals', 2, 115),

('The Weather', 'The weather changes every day. Today it is sunny and warm. I like sunny days. On sunny days, I play outside with my friends. Sometimes the weather is cloudy. When it is cloudy, the sky is grey. It often rains on cloudy days. Rain makes the flowers grow. In winter, it is cold and sometimes it snows. Snow is white and soft. Children love to play in the snow. In summer, the weather is hot. We go swimming in the pool. What is your favorite weather?', 'A1', 'Weather', 2, 118),

('My School', 'My school is big and beautiful. It has twenty classrooms. There is a library in my school. I go to the library to read books. My school also has a sports field. We play football and basketball there. My favorite subject is English. My English teacher is very kind. She teaches us new words every day. My school starts at 8 in the morning and finishes at 3 in the afternoon. I have many friends at school. We eat lunch together in the cafeteria. I love my school.', 'A1', 'Education', 2, 112),

('Colors and Clothes', 'I like wearing colorful clothes. My favorite color is blue. I have a blue shirt and blue jeans. My shoes are white. My sister likes the color pink. She has a pink dress. My father wears a black suit to work. My mother likes green. She has a green coat. Colors make our life beautiful. Red is the color of apples and fire trucks. Yellow is the color of the sun and bananas. Orange is a fruit and also a color. What is your favorite color?', 'A1', 'Clothing', 2, 108),

('Numbers and Shopping', 'I went shopping with my mother yesterday. We went to the supermarket. We bought bread, milk, and eggs. The bread cost two dollars. The milk cost three dollars. The eggs cost four dollars. We paid ten dollars in total. The cashier gave us one dollar back. I like shopping. I can see many things in the supermarket. There are fruits, vegetables, and drinks. There is also a toy section. I wanted to buy a toy car. It cost fifteen dollars. My mother said maybe next time.', 'A1', 'Shopping', 2, 115),

('Sports and Games', 'I love playing sports. My favorite sport is football. I play football with my friends every weekend. Football is played with a round ball. Two teams play against each other. Each team tries to kick the ball into the goal. I also like swimming. Swimming is good exercise for the whole body. In school, we play basketball. Basketball is played with an orange ball. Players throw the ball into a basket. My sister likes tennis. She plays tennis on Saturdays. Sports keep us healthy and happy.', 'A1', 'Sports', 2, 112),

('My House', 'I live in a big house. My house has two floors. On the first floor, there is a living room, a kitchen, and a bathroom. The living room has a sofa and a television. We watch TV together in the evenings. The kitchen has a table and four chairs. We eat our meals in the kitchen. On the second floor, there are three bedrooms. I have my own bedroom. My bedroom has a bed, a desk, and a wardrobe. There is a garden behind my house. I play in the garden on sunny days.', 'A1', 'Home', 2, 116),

('Hobbies', 'Everybody has hobbies. A hobby is something you enjoy doing in your free time. My hobby is drawing. I draw pictures of animals and people. My best friend''s hobby is reading books. She reads every evening before bed. My brother likes playing video games. He plays games on his computer. My father''s hobby is gardening. He grows tomatoes and cucumbers. My mother likes cooking. She tries new recipes every week. Hobbies make us happy and help us relax. What is your hobby?', 'A1', 'Hobbies', 2, 110),

('Seasons', 'There are four seasons in a year. The seasons are spring, summer, autumn, and winter. Spring comes after winter. In spring, flowers bloom and birds sing. The weather is warm and nice. Summer is the hottest season. We go on vacation in summer. Children do not go to school. Autumn comes after summer. Leaves turn yellow, orange, and red in autumn. Winter is the coldest season. We wear warm clothes in winter. It sometimes snows in winter. My favorite season is summer because I can swim and play outside.', 'A1', 'Nature', 2, 112),

('Fruits and Vegetables', 'Fruits and vegetables are very healthy. We should eat them every day. Common fruits are apples, bananas, oranges, and grapes. Apples are red or green. Bananas are yellow and sweet. Oranges are round and orange. Grapes can be red, green, or purple. Common vegetables are carrots, potatoes, tomatoes, and onions. Carrots are orange and good for eyes. Potatoes can be boiled, fried, or baked. Tomatoes are red and used in many dishes. Onions have a strong smell. Eat five portions of fruits and vegetables each day.', 'A1', 'Food', 2, 114),

('Transport', 'People use different types of transport. In cities, many people use buses and trains. Buses stop at bus stops. Trains travel on railways. Some people drive cars. Cars travel on roads. Bicycles are popular in many countries. Bicycles are good for health and the environment. Airplanes travel through the sky. They are the fastest way to travel long distances. Ships travel on water. They carry people and goods across the sea. My family has a car. We use it to go on holiday. I go to school by bus every day.', 'A1', 'Transport', 2, 112),

('Days of the Week', 'There are seven days in a week. The days are Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, and Sunday. Monday is the first day of the week. The week starts on Monday. Friday is the last day of the school week. Saturday and Sunday are the weekend. I do not go to school on weekends. On Saturday, I play with my friends. On Sunday, my family goes to church or visits grandparents. My favorite day is Saturday. I can sleep late and do what I want. What is your favorite day of the week?', 'A1', 'Time', 2, 112),

('Body Parts', 'Our body has many parts. The head is at the top of our body. We have two eyes to see. We have two ears to hear. Our nose helps us smell things. Our mouth helps us eat and talk. We have two arms with hands at the end. Each hand has five fingers. We have two legs with feet at the bottom. Each foot has five toes. Our heart is inside our chest. It pumps blood around our body. Our brain is inside our head. It controls everything we do. We must take care of our body by eating well and exercising.', 'A1', 'Health', 2, 115),

('At the Restaurant', 'Yesterday my family went to a restaurant. The restaurant was beautiful and clean. A waiter came to our table. He gave us a menu. A menu is a list of food and drinks. I ordered a pizza and orange juice. My mother ordered pasta and water. My father ordered steak and coffee. The food was delicious. After eating, we asked for the bill. The total was forty dollars. My father paid with a credit card. The waiter was very friendly. We left a tip for good service. I love going to restaurants with my family.', 'A1', 'Daily Life', 2, 114),

('Months of the Year', 'There are twelve months in a year. January is the first month. It is cold in January. February is the second month. Valentine''s Day is in February. March, April, and May are spring months. June, July, and August are summer months. Schools usually close in summer. September is the first month of autumn. October and November are also autumn months. December is the last month of the year. Christmas is in December. My birthday is in July. I love summer because I have a holiday. What month is your birthday?', 'A1', 'Time', 2, 112),

('My Pet', 'I have a pet dog. His name is Max. Max is two years old. He is brown with white spots. Max likes to play in the garden. He runs and jumps all day. Every morning, I give Max food and water. I walk Max in the park every evening. Max loves meeting other dogs. He wags his tail when he is happy. Sometimes Max sleeps in my room. He sleeps on a small bed near my desk. Max is very loyal and friendly. He barks when strangers come to our house. I love Max very much. Pets are great companions.', 'A1', 'Animals', 2, 112),

('A Trip to the Beach', 'Last summer, my family went to the beach. The beach was beautiful. The sand was white and soft. The sea was blue and warm. I swam in the sea with my brother. We also built a sandcastle. My mother sat under an umbrella and read a book. My father went fishing. He caught three fish. We had a picnic on the beach. We ate sandwiches and drank lemonade. In the evening, we watched the sunset. The sky turned pink and orange. It was a magical moment. I want to go to the beach again next summer.', 'A1', 'Travel', 2, 114),

-- A2 LEVEL (20 ta)
('The History of Pizza', 'Pizza is one of the most popular foods in the world. It originally came from Italy. The first pizzas were simple flat breads with tomato and cheese. In Naples, Italy, pizza became very popular in the 18th century. Italian immigrants brought pizza to America in the late 1800s. In New York, the first pizzeria opened in 1905. During World War II, American soldiers in Italy tried pizza and loved it. When they returned home, they wanted pizza in America too. Today, pizza is eaten in almost every country. There are hundreds of different types of pizza. The most classic is the Margherita, which has tomato, mozzarella, and basil.', 'A2', 'Food', 3, 145),

('Social Media and Young People', 'Social media has changed the way young people communicate. Platforms like Instagram, TikTok, and YouTube are used by millions of teenagers every day. Many young people share photos, videos, and thoughts online. Social media can be positive. It helps people stay connected with friends and family. It is also a place to learn new things. However, there are some problems. Some young people spend too much time on their phones. This can affect their studies and sleep. Cyberbullying is also a problem on social media. Parents and teachers should help young people use social media responsibly.', 'A2', 'Technology', 3, 140),

('Healthy Eating Habits', 'Eating healthy is very important for our body and mind. A balanced diet includes fruits, vegetables, proteins, and carbohydrates. Fruits and vegetables give us vitamins and minerals. Proteins like meat, fish, and eggs help our muscles grow. Carbohydrates like bread and rice give us energy. We should drink at least eight glasses of water every day. Water helps our body function properly. Fast food and sugary drinks should be eaten only occasionally. They contain too much fat and sugar. Skipping breakfast is a bad habit. Breakfast gives us energy for the whole day. Try to eat three regular meals a day.', 'A2', 'Health', 3, 138),

('The Olympic Games', 'The Olympic Games are the biggest sporting event in the world. They are held every four years. There are two types of Olympics: the Summer Olympics and the Winter Olympics. The first modern Olympics were held in Athens, Greece in 1896. Athletes from around the world compete in different sports. In the Summer Olympics, sports include swimming, athletics, gymnastics, and cycling. In the Winter Olympics, sports include skiing, ice skating, and snowboarding. Winners receive gold, silver, or bronze medals. The Olympic motto is "Faster, Higher, Stronger." The Olympic flag has five colored rings. Each ring represents a continent of the world.', 'A2', 'Sports', 3, 142),

('Going Green: Simple Steps', 'Climate change is a serious problem. We can all help protect our planet by making small changes. First, we can save energy at home. Turn off lights when you leave a room. Use energy-saving light bulbs. Second, reduce plastic use. Bring your own bag when shopping. Say no to plastic straws. Third, recycle paper, glass, and metal. Fourth, use public transport or a bicycle instead of a car. Cars produce a lot of carbon dioxide. Fifth, eat less meat. Meat production uses a lot of water and land. Small changes in our daily habits can make a big difference for the environment.', 'A2', 'Environment', 3, 138),

('A Visit to London', 'London is the capital city of England and the United Kingdom. It is one of the most visited cities in the world. The city is famous for its history, culture, and landmarks. The most famous landmark is Big Ben, the large clock tower near the Houses of Parliament. The Tower of London is a historic castle by the River Thames. Buckingham Palace is where the King lives. The London Eye is a giant Ferris wheel with great views of the city. London has excellent museums, many of which are free. The British Museum has ancient artifacts from around the world. London is also a multicultural city with people from many different countries.', 'A2', 'Travel', 3, 145),

('Music and Its Effects', 'Music is a universal language. People all over the world enjoy music. Research shows that music has many positive effects on our health. Listening to music can reduce stress and anxiety. It can improve our mood when we are sad. Music can also help us concentrate when we are studying. Many students listen to classical music while doing homework. Playing a musical instrument is especially beneficial. It improves memory, coordination, and creativity. Music therapy is used to help patients in hospitals. Singing in a choir can make people feel part of a community. Whether you listen or play, music enriches our lives in many ways.', 'A2', 'Arts', 3, 142),

('Water: The Precious Resource', 'Water is essential for all living things on Earth. Our bodies are about 60% water. We need water to survive. We use water for drinking, cooking, and cleaning. Farmers use water to grow food. Industries use water to make products. Despite covering 71% of the Earth''s surface, most water is salty ocean water. Only 3% of water on Earth is fresh water. Of this, most is frozen in glaciers. Only a small amount is available for drinking. Water pollution is a major problem in many countries. Factories and farms can pollute rivers and lakes. We should use water carefully and not waste it.', 'A2', 'Environment', 3, 142),

('The Internet: Advantages and Disadvantages', 'The internet has changed our world dramatically. It was invented in the 1960s and became widely available in the 1990s. Today, billions of people use the internet every day. The internet has many advantages. We can find information on any topic in seconds. We can communicate with people anywhere in the world. We can shop, bank, and work online. Entertainment like movies and music is available instantly. However, the internet also has disadvantages. Some websites contain false information. Children can access inappropriate content. People can become addicted to social media. Privacy is also a concern. Our personal data can be collected and used without our knowledge. We should use the internet wisely.', 'A2', 'Technology', 4, 155),

('Traditional Uzbek Cuisine', 'Uzbek cuisine is one of the richest in Central Asia. The most famous dish is plov, also known as pilaf. Plov is made with rice, meat, carrots, and onions. It is cooked in a large round pot called a kazan. Another popular dish is shurpa, a hearty soup with meat and vegetables. Samsa are triangular pastries filled with meat and onion. They are baked in a clay oven called a tandoor. Bread, called non, is very important in Uzbek culture. It is baked in the tandoor and has a unique taste. Uzbek people are known for their hospitality. Guests are always offered tea and sweets.', 'A2', 'Culture', 3, 140),

('Reading for Pleasure', 'Reading is one of the most beneficial habits we can develop. Regular reading improves our vocabulary and language skills. When we read, we encounter new words and expressions. Reading also improves our concentration and focus. Unlike watching TV, reading requires active mental engagement. Fiction books allow us to experience different lives and cultures. Non-fiction books teach us about the real world. Reading before bed can help us relax and sleep better. Many successful people say reading is one of their most important habits. You do not need to read long books. Even reading for 20 minutes a day can make a big difference. Find a topic you enjoy and start reading today.', 'A2', 'Education', 3, 142),

('The Life of a Student', 'Being a student is both exciting and challenging. Students spend most of their day in school, learning different subjects. After school, they have homework and revision to do. Time management is very important for students. A good student plans their study time carefully. They do not leave everything until the last minute. Students also need time to relax and socialize. Spending time with friends and enjoying hobbies is important for mental health. Sleep is also crucial. Teenagers need at least 8-9 hours of sleep each night. A healthy diet and regular exercise help students perform better academically. University students face additional challenges like living alone and managing money.', 'A2', 'Education', 3, 138),

('Wild Animals in Danger', 'Many wild animals around the world are in danger of extinction. Extinction means a species completely disappears from the Earth. Tigers, elephants, and giant pandas are all endangered species. The main cause of extinction is habitat destruction. When humans cut down forests or build cities, animals lose their homes. Pollution is another serious problem. It contaminates the water and food that animals depend on. Hunting and poaching also threaten many species. Organizations like the WWF work to protect endangered animals. They create nature reserves where animals can live safely. We all have a responsibility to protect wildlife for future generations.', 'A2', 'Environment', 3, 140),

('A Day in a Hospital', 'Hospitals are very busy places. Doctors, nurses, and other staff work hard to help sick people. When a patient arrives at a hospital, they first go to reception. A receptionist takes their details and sends them to see a doctor. The doctor examines the patient and asks about their symptoms. They may order blood tests or X-rays. Depending on the diagnosis, the patient may receive medicine or need an operation. Nurses look after patients in the wards. They check temperature, blood pressure, and give medicine. Some patients stay in hospital for several days. Hospitals have special departments for different conditions, such as the emergency room and the maternity ward.', 'A2', 'Health', 3, 142),

('Money and Saving', 'Managing money is an important life skill. Many young people do not learn about money at school. Understanding how to save and spend wisely can prevent financial problems later in life. A budget is a plan for how to use your money. It shows how much you earn and how much you spend. The golden rule of saving is: spend less than you earn. Put some money aside each month, even if it is a small amount. Avoid spending on things you do not need. Credit cards can be useful but dangerous. If you spend more than you can pay back, you will have debt. Learning to save early in life creates good habits for the future.', 'A2', 'Finance', 3, 140),

('The Solar System', 'Our solar system consists of the Sun and everything that orbits around it. The Sun is a star at the center of our solar system. It provides light and heat to all planets. There are eight planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Earth is the third planet from the Sun and the only planet known to have life. Jupiter is the largest planet. Saturn is famous for its beautiful rings made of ice and rock. Mars is called the Red Planet because of its reddish soil. Scientists believe that Mars may have had water in the past. Space exploration continues to reveal new discoveries about our solar system.', 'A2', 'Science', 3, 145),

('Cooking at Home', 'Cooking at home has many benefits. It is healthier than eating out because you know exactly what ingredients you are using. Home cooking is also cheaper. Restaurant meals can be very expensive. Cooking is also a creative activity. You can experiment with different ingredients and create new recipes. Many people find cooking relaxing and enjoyable. Learning to cook basic meals is an important life skill. Start with simple dishes like pasta, omelettes, or soup. Follow recipes carefully when you are a beginner. As you gain confidence, you can try more complex dishes. Cooking for others is a wonderful way to show care and love. Share meals with family and friends whenever you can.', 'A2', 'Food', 3, 138),

('City Life vs Country Life', 'Many people debate whether it is better to live in a city or in the countryside. City life offers many opportunities. There are more jobs, better hospitals, and more entertainment. Public transport makes it easy to get around without a car. However, cities can be noisy, crowded, and expensive. Air pollution is a problem in many large cities. Country life, on the other hand, is quieter and cleaner. Nature is all around you. The cost of living is usually lower. However, there are fewer job opportunities and services may be far away. Public transport is limited. Many people choose to live in suburbs, which offer a balance between city and country living.', 'A2', 'Society', 3, 140),

('Learning a Foreign Language', 'Learning a foreign language is one of the most valuable things you can do. It opens doors to new cultures and opportunities. English is the most widely spoken language in the world. It is used in international business, science, and culture. Spanish is the second most spoken language. Mandarin Chinese is spoken by the most native speakers. The best way to learn a language is through practice. Speak the language as much as possible. Watch movies and TV shows in the language. Read books and listen to music. Use language learning apps like Duolingo. Do not be afraid of making mistakes. Mistakes are part of the learning process. Even a basic knowledge of another language is useful.', 'A2', 'Education', 3, 140),

('Volunteering', 'Volunteering means giving your time and skills to help others without being paid. Millions of people around the world volunteer in their communities. You can volunteer at hospitals, schools, animal shelters, or food banks. Volunteering has many benefits. It helps people in need. It also benefits the volunteer. You learn new skills and gain experience. Volunteering looks good on a CV when applying for jobs. It helps you meet new people and build friendships. Studies show that volunteering makes people happier and reduces stress. Even a few hours per month can make a significant difference. Young people especially benefit from volunteering as it teaches responsibility and empathy.', 'A2', 'Society', 3, 138),

-- B1 LEVEL (20 ta)
('The Psychology of Habits', 'Habits shape our daily lives in profound ways. According to researchers, approximately 40% of our daily actions are habitual rather than conscious decisions. A habit consists of three components: a cue, a routine, and a reward. The cue triggers the behavior. The routine is the behavior itself. The reward reinforces it. Understanding this loop is the first step to changing unwanted habits. To build a new habit, attach it to an existing one. This is called habit stacking. For example, if you want to start meditating, do it right after brushing your teeth. Consistency is more important than intensity when building habits. Small, daily actions compound over time into significant results.', 'B1', 'Psychology', 4, 155),

('Artificial Intelligence in Daily Life', 'Artificial intelligence, or AI, is no longer science fiction. It is part of our daily lives in many ways we may not even notice. When you ask Siri or Google Assistant a question, you are using AI. When Netflix recommends a film you might enjoy, that is AI analyzing your viewing habits. Email spam filters use AI to identify unwanted messages. Self-driving car technology relies heavily on AI. In healthcare, AI can analyze medical images to detect diseases like cancer with remarkable accuracy. In education, AI-powered tutoring systems can personalize learning for individual students. While AI offers tremendous benefits, it also raises important questions about privacy, employment, and ethical decision-making.', 'B1', 'Technology', 4, 158),

('The Importance of Sleep', 'Sleep is often undervalued in our busy modern society. Many people sacrifice sleep to work longer or spend more time on screens. However, research consistently shows that adequate sleep is essential for physical and mental health. During sleep, the brain consolidates memories and processes information learned during the day. The body repairs tissues and produces hormones during deep sleep. Adults need between 7-9 hours of sleep per night. Teenagers require 8-10 hours. Chronic sleep deprivation is linked to increased risk of obesity, diabetes, heart disease, and depression. Poor sleep also impairs concentration, decision-making, and emotional regulation. Establishing a regular sleep schedule and avoiding screens before bed are effective strategies for improving sleep quality.', 'B1', 'Health', 4, 158),

('Globalization: Benefits and Challenges', 'Globalization refers to the increasing interconnection of countries through trade, technology, and culture. Over the past century, and especially since the internet revolution, the world has become more connected than ever. Globalization has brought undeniable benefits. It has lifted millions of people out of poverty in developing countries. It has increased access to goods, services, and information. Cultural exchange has enriched societies worldwide. However, globalization also presents challenges. Income inequality has grown, with the benefits of globalization not evenly distributed. Local cultures and languages face pressure from dominant global cultures. Environmental problems like climate change require global cooperation to solve. The challenge for the modern world is to maximize the benefits of globalization while minimizing its negative effects.', 'B1', 'Society', 4, 162),

('The Human Brain', 'The human brain is the most complex organ in the known universe. Weighing approximately 1.4 kilograms, it contains around 86 billion neurons. These neurons communicate through trillions of connections called synapses. The brain controls all functions of the body, including thought, memory, emotion, and movement. It is divided into two hemispheres: the left and the right. The left hemisphere generally controls language and logical thinking. The right hemisphere is associated with creativity and spatial awareness. The prefrontal cortex, located at the front of the brain, is responsible for decision-making and impulse control. Remarkably, the brain can reorganize itself through a process called neuroplasticity, meaning we can literally change our brains through learning and experience.', 'B1', 'Science', 4, 158),

('Urbanization and Its Effects', 'Urbanization, the movement of people from rural to urban areas, is one of the defining trends of our time. In 1950, about 30% of the world''s population lived in cities. Today, the figure is over 55%, and it is projected to reach 68% by 2050. Cities offer economic opportunities, better healthcare, and more diverse social environments. However, rapid urbanization creates significant challenges. Housing shortages drive up property prices, making cities unaffordable for many. Traffic congestion and pollution reduce quality of life. Informal settlements, known as slums, develop when cities cannot provide adequate housing for newcomers. Effective urban planning is crucial to ensure that growing cities remain livable, sustainable, and equitable for all residents.', 'B1', 'Society', 4, 158),

('The Benefits of Exercise', 'Physical exercise is one of the most powerful medicines available to us. Regular exercise reduces the risk of numerous chronic diseases, including heart disease, type 2 diabetes, and several forms of cancer. It strengthens muscles and bones, improves cardiovascular health, and helps maintain a healthy weight. Beyond the physical benefits, exercise has profound effects on mental health. It triggers the release of endorphins, neurotransmitters that reduce pain and create feelings of wellbeing. Regular physical activity is as effective as antidepressants for treating mild to moderate depression. Exercise also improves sleep quality, enhances cognitive function, and boosts self-esteem. Health guidelines recommend at least 150 minutes of moderate-intensity exercise per week.', 'B1', 'Health', 4, 155),

('Climate Change: Causes and Solutions', 'Climate change is arguably the most significant challenge facing humanity in the 21st century. The Earth''s average temperature has risen by approximately 1.1 degrees Celsius since the industrial revolution. The primary cause is the increased concentration of greenhouse gases, particularly carbon dioxide and methane, in the atmosphere. These gases trap heat from the sun, warming the planet. The consequences of climate change include more frequent extreme weather events, rising sea levels, and disruption to ecosystems. To address climate change, we must transition from fossil fuels to renewable energy sources such as solar and wind power. Reducing deforestation and improving energy efficiency are also critical steps. International cooperation, as seen in the Paris Agreement, is essential.', 'B1', 'Environment', 4, 162),

('The Power of Reading', 'Reading is considered by many experts to be the single most important intellectual activity we can engage in. Unlike passive media such as television, reading is an active process that requires and develops numerous cognitive skills. Reading fiction improves our ability to empathize with others, as we inhabit the perspectives of characters different from ourselves. Non-fiction reading expands our knowledge of the world. Both types of reading build vocabulary and improve writing skills. Studies have shown that regular reading correlates with higher academic achievement, better job prospects, and even a reduced risk of Alzheimer''s disease in old age. In an age of social media and short-form content, developing a sustained reading practice is more valuable than ever.', 'B1', 'Education', 4, 155),

('Renewable Energy', 'The transition from fossil fuels to renewable energy is one of the most important challenges of our time. Renewable energy comes from natural sources that are constantly replenished, such as sunlight, wind, rain, tides, and geothermal heat. Solar power has experienced a dramatic reduction in cost over the past decade, making it competitive with fossil fuels in many markets. Wind energy is now the cheapest source of electricity in many parts of the world. Hydropower has been generating electricity for over a century and provides about 16% of global electricity. The main challenge for renewable energy is intermittency — the sun does not always shine, and the wind does not always blow. Developing better energy storage solutions, particularly batteries, is therefore crucial.', 'B1', 'Environment', 4, 160),

('Cultural Differences in Communication', 'Communication styles vary significantly across cultures, and misunderstandings can arise when people from different cultural backgrounds interact. Some cultures are described as "high-context," meaning that much communication is implicit and depends on shared understanding. Japan and many Arab countries are examples of high-context cultures. Other cultures are "low-context," with communication that is direct and explicit. The United States and Germany are generally considered low-context cultures. Attitudes toward silence also differ. In some cultures, silence in conversation is comfortable and respectful. In others, silence creates awkward situations. Nonverbal communication, including eye contact, physical distance, and gestures, also varies enormously across cultures. Understanding these differences is essential for effective international business and diplomacy.', 'B1', 'Culture', 4, 158),

('The History of the Internet', 'The internet has transformed human civilization in ways that rival the invention of printing. Its origins lie in ARPANET, a US military network created in 1969 that could survive a nuclear attack by routing messages around damaged nodes. In 1991, Tim Berners-Lee invented the World Wide Web, making the internet accessible to ordinary people. The 1990s saw an explosion of commercial websites and internet users. The early 2000s brought broadband, enabling faster connections. Social media emerged in the mid-2000s with platforms like Facebook and YouTube. The smartphone revolution, beginning with the iPhone in 2007, made the internet mobile and always accessible. Today, approximately 5 billion people use the internet, representing nearly two-thirds of the world''s population.', 'B1', 'Technology', 4, 158),

('Stress and How to Manage It', 'Stress is the body''s response to challenging situations. When we perceive a threat, the brain triggers the release of hormones like adrenaline and cortisol. These cause the "fight or flight" response: increased heart rate, faster breathing, and heightened alertness. In short bursts, this response is useful. However, chronic stress, when the stress response is constantly activated, is harmful to health. It can lead to anxiety, depression, digestive problems, and cardiovascular disease. Effective stress management techniques include regular exercise, which burns off stress hormones. Mindfulness meditation teaches us to observe thoughts without reacting to them. Deep breathing activates the parasympathetic nervous system, counteracting the stress response. Maintaining social connections provides emotional support during difficult times.', 'B1', 'Health', 4, 160),

('The Art of Negotiation', 'Negotiation is a fundamental life skill that we use more often than we might think. Whether discussing a salary, resolving a conflict with a friend, or buying a car, negotiation skills are valuable. Effective negotiation begins with preparation. Know what you want and what your alternatives are. Understanding the other party''s interests and needs is equally important. Focus on interests, not positions. A position is what someone says they want. An interest is the underlying reason why they want it. Often, creative solutions can satisfy both parties'' interests even when their positions seem incompatible. Active listening is crucial in negotiation. Make the other person feel understood. Avoid making negotiations personal. Separate the people from the problem.', 'B1', 'Business', 4, 155),

('Photography as an Art Form', 'Photography, since its invention in the early 19th century, has evolved from a purely technical process to a recognized art form. A photograph can capture a fleeting moment and preserve it forever. Great photographers develop a distinctive eye for composition, light, and subject matter. The rule of thirds suggests that the most important elements of an image should be placed at the intersections of a grid dividing the image into nine equal parts. Light is perhaps the most critical element in photography. The "golden hour" — the period shortly after sunrise and before sunset — produces particularly beautiful, warm light. Digital technology has democratized photography, allowing anyone with a smartphone to take and share images. Yet the fundamental artistic principles remain the same.', 'B1', 'Arts', 4, 155),

('Economic Inequality', 'Economic inequality — the gap between the rich and the poor — has grown in most countries over the past four decades. According to Oxfam, the 26 wealthiest individuals in the world own as much wealth as the poorest 50% of humanity. The causes of inequality are complex and debated. Technological change has increased the rewards for highly skilled workers while reducing demand for routine jobs. Globalization has benefited some workers while displacing others. Tax policies in many countries have favored the wealthy. The consequences of extreme inequality are concerning. High inequality is associated with lower social mobility, worse health outcomes, and higher crime rates. Policies such as progressive taxation, investment in education, and stronger labor rights can help reduce inequality.', 'B1', 'Society', 4, 158),

('The Science of Nutrition', 'Nutrition science examines how the food we eat affects our health. Our diet consists of macronutrients — carbohydrates, proteins, and fats — and micronutrients, including vitamins and minerals. Carbohydrates are the body''s primary energy source. Complex carbohydrates, found in whole grains and vegetables, are digested slowly and provide sustained energy. Simple carbohydrates, found in sugar and refined grains, cause rapid spikes in blood sugar. Proteins are essential for building and repairing tissues. The quality of fat in the diet matters greatly. Unsaturated fats, found in olive oil, nuts, and fish, are beneficial for heart health. Trans fats, found in many processed foods, increase the risk of heart disease. The Mediterranean diet, rich in fruits, vegetables, fish, and olive oil, is consistently ranked as one of the healthiest.', 'B1', 'Health', 4, 162),

('Space Exploration', 'The exploration of space represents one of humanity''s greatest intellectual and technical achievements. The Space Age began on October 4, 1957, when the Soviet Union launched Sputnik, the first artificial satellite. In 1961, Yuri Gagarin became the first human to orbit Earth. The United States responded with the Apollo program, which landed astronauts on the Moon in 1969. After the end of the Cold War, international cooperation in space increased. The International Space Station, a joint project involving 15 countries, has been continuously inhabited since 2000. Today, a new era of space exploration is underway, driven partly by private companies like SpaceX and Blue Origin. Plans for human missions to Mars are being developed. Space exploration has produced numerous technological benefits, from GPS to memory foam.', 'B1', 'Science', 4, 162),

('The Fashion Industry', 'The global fashion industry is worth over two trillion dollars and employs approximately 300 million people worldwide. Fashion reflects cultural values and social change. In the 20th century, fashion democratized as mass production made stylish clothing affordable. Designers like Coco Chanel revolutionized women''s fashion by prioritizing comfort and practicality. The rise of fast fashion in the 1990s and 2000s allowed consumers to buy cheap, trendy clothing. However, fast fashion has significant environmental and social costs. The fashion industry is responsible for 10% of global carbon emissions. Many garment workers in developing countries work in poor conditions for low wages. The sustainable fashion movement encourages consumers to buy less but better quality clothing, and to choose brands with ethical practices.', 'B1', 'Culture', 4, 158),

('The Role of Women in Society', 'The status of women in society has changed dramatically over the past century. In most Western countries at the start of the 20th century, women could not vote, could not own property, and had very limited access to education and professional careers. The feminist movement fought for and achieved many of these rights. Today, women in many countries have equal legal rights with men. Women represent about half of the workforce in most developed countries. However, significant inequalities remain. Women are still underrepresented in leadership positions in business and politics. The gender pay gap persists in most countries. Women still perform a disproportionate share of unpaid domestic and care work. In many parts of the developing world, women still face severe restrictions on their freedom and opportunities.', 'B1', 'Society', 4, 162),

-- B2 LEVEL (20 ta)
('The Neuroscience of Creativity', 'Creativity has long been considered a mysterious, almost magical process. Recent advances in neuroscience, however, are beginning to reveal its biological basis. Contrary to the popular belief that creativity is a right-brain activity, neuroimaging studies show that creative thinking engages an extensive network of brain regions, including the default mode network, which is active during daydreaming and imagination. The most creative moments often occur when we are not actively focusing on a problem — in the shower, on a walk, or just before sleep. This is when the default mode network is most active, making surprising connections between seemingly unrelated ideas. Studies suggest that creative people have greater connectivity between different brain networks and can switch between focused attention and relaxed, associative thinking more fluidly.', 'B2', 'Science', 5, 175),

('The Ethics of Artificial Intelligence', 'As artificial intelligence systems become increasingly capable and pervasive, the ethical questions they raise become ever more pressing. Bias in AI is a significant concern. Since AI systems learn from historical data, they can perpetuate and even amplify existing social biases. Facial recognition systems, for example, have been shown to be less accurate for women and people with darker skin tones. Autonomous weapons — drones or robots that can make lethal decisions without human intervention — raise profound moral questions about accountability. The potential economic disruption caused by AI automation threatens millions of jobs. Perhaps most fundamental is the question of transparency: when an AI system makes a consequential decision, such as denying someone a loan or parole, can its reasoning be understood and challenged?', 'B2', 'Technology', 5, 178),

('Cognitive Biases and Decision Making', 'Human thinking is fundamentally flawed in predictable ways. Cognitive biases are systematic errors in thinking that affect our judgments and decisions. The confirmation bias leads us to seek and interpret information in ways that confirm our existing beliefs. The availability heuristic causes us to overestimate the likelihood of events that come easily to mind. The sunk cost fallacy leads us to continue investing in failing projects because of the resources already committed. Loss aversion means we feel the pain of losses more acutely than equivalent gains, which can lead to irrational risk-averse behavior. Understanding these biases does not eliminate them, but awareness is the first step. Strategies such as seeking disconfirming evidence, using systematic decision frameworks, and soliciting outside perspectives can help mitigate the effects of cognitive biases.', 'B2', 'Psychology', 5, 175),

('The Philosophy of Time', 'Time is one of the most fundamental and mysterious aspects of our experience. Philosophers have debated its nature for millennia. The "A-theory" of time holds that there is an objective distinction between past, present, and future, and that events genuinely move from future to present to past. The "B-theory," on the other hand, holds that all moments in time are equally real, and that past, present, and future are merely perspectival distinctions — like "here" and "there" in space. Physics complicates our intuitive understanding of time. Einstein''s theory of special relativity shows that time passes at different rates for observers in relative motion. There is no single universal present. The thermodynamic arrow of time — the reason time seems to flow in one direction — is related to the increase of entropy, or disorder.', 'B2', 'Philosophy', 5, 178),

('Antibiotic Resistance: A Global Crisis', 'Antibiotic resistance is one of the most serious threats to global public health. Since Alexander Fleming discovered penicillin in 1928, antibiotics have saved hundreds of millions of lives by treating bacterial infections. However, bacteria evolve resistance to antibiotics through natural selection. Each time antibiotics are used, bacteria that happen to be resistant survive and reproduce. The overuse and misuse of antibiotics has dramatically accelerated this process. Antibiotics are frequently prescribed unnecessarily for viral infections, against which they are ineffective. In many countries, antibiotics are available without prescription. In agriculture, they are routinely administered to healthy animals to promote growth. If current trends continue, antibiotic-resistant infections could kill 10 million people per year by 2050. New antibiotics are urgently needed, but developing them is costly and commercially unattractive.', 'B2', 'Health', 5, 178),

('The Psychology of Persuasion', 'In his seminal work, psychologist Robert Cialdini identified six principles of influence that underlie most persuasive communication. Reciprocity exploits our tendency to return favors. If someone gives us something, we feel obligated to give back. This is why free samples and gifts are such effective marketing tools. Social proof leverages our tendency to look to others for guidance on how to behave. We are more likely to try a restaurant if it has a long queue outside. Authority induces compliance because we are conditioned to respect expertise and credentials. Scarcity makes things seem more desirable when they are rare or diminishing. Commitment and consistency describe our tendency to behave in ways consistent with our prior actions and stated positions. Liking simply acknowledges that we are more easily persuaded by people we like.', 'B2', 'Psychology', 5, 175),

('Quantum Mechanics: A Conceptual Overview', 'Quantum mechanics is the branch of physics that describes the behavior of matter and energy at the atomic and subatomic scale. It is arguably the most successful scientific theory ever developed, yet its implications remain deeply counterintuitive and philosophically controversial. At the quantum scale, objects do not have definite properties until they are measured. An electron, for example, does not have a definite position until we observe it. Before measurement, it exists in a superposition of multiple possible states simultaneously. This is not merely a reflection of our ignorance but a fundamental feature of nature, as demonstrated by the famous double-slit experiment. The phenomenon of quantum entanglement, where particles remain correlated regardless of the distance between them, has been experimentally verified and has no classical analogue.', 'B2', 'Science', 5, 178),

('Sustainable Development Goals', 'In 2015, the United Nations adopted the Sustainable Development Goals, a universal call to action to end poverty, protect the planet, and ensure that all people enjoy peace and prosperity by 2030. The 17 goals encompass a wide range of issues, from eliminating extreme poverty and hunger to ensuring quality education, gender equality, clean water, and climate action. Progress has been made on many fronts. The proportion of people living in extreme poverty has declined significantly. Child mortality has fallen dramatically. However, the COVID-19 pandemic set back progress on multiple goals, pushing millions back into poverty and disrupting education systems worldwide. Achieving the SDGs requires unprecedented levels of international cooperation, financing, and political will, particularly from wealthy nations.', 'B2', 'Society', 5, 175),

('The Literature of Dystopia', 'Dystopian fiction, which depicts nightmare futures, has become one of the most significant and popular literary genres of the modern era. George Orwell''s Nineteen Eighty-Four, published in 1949, imagined a totalitarian state in which Big Brother''s surveillance is omnipresent and language itself is manipulated to prevent dissident thought. Aldous Huxley''s Brave New World, published in 1932, presented a contrasting dystopia in which control is achieved not through fear but through pleasure and consumption. Margaret Atwood''s The Handmaid''s Tale explores the subjugation of women in a theocratic state. What makes these works enduring is their contemporary relevance. As technology advances and political freedoms come under pressure in many parts of the world, these fictional warnings seem increasingly pertinent.', 'B2', 'Literature', 5, 175),

('Behavioral Economics', 'Traditional economics assumes that people are rational agents who make decisions to maximize their self-interest. Behavioral economics challenges this assumption, drawing on insights from psychology to understand how people actually make decisions. Richard Thaler and Cass Sunstein introduced the concept of "nudging" — designing choice environments to steer people towards better decisions without restricting their freedom. For example, automatically enrolling employees in pension schemes dramatically increases participation rates. Mental accounting refers to our tendency to treat money differently depending on its source or intended use. We might spend a windfall more freely than earned income, even though a dollar is a dollar regardless of its origin. Behavioral economics has had significant practical applications in public policy, healthcare, and financial planning.', 'B2', 'Economics', 5, 175),

('The History of Medicine', 'The history of medicine is a story of gradual triumph over ignorance and disease. For most of human history, illness was attributed to supernatural causes, and treatments often involved prayer, ritual, or harmful practices such as bloodletting. The ancient Greeks made significant advances, with Hippocrates establishing medicine as a rational discipline based on observation. The scientific revolution of the 17th century brought new understanding of anatomy and physiology. In the 19th century, germ theory — the understanding that many diseases are caused by microorganisms — transformed medicine. Antiseptic techniques, developed by Joseph Lister, dramatically reduced deaths from surgical infections. The 20th century saw the development of vaccines, antibiotics, and advanced surgical techniques. The mapping of the human genome at the start of the 21st century opened new frontiers in personalized medicine.', 'B2', 'Science', 5, 178),

('Language and Identity', 'Language is intimately connected to identity — both personal and cultural. The language we speak shapes how we perceive and categorize the world. The Sapir-Whorf hypothesis proposes that the structure of a language affects its speakers'' worldview. Strong versions of this hypothesis are generally rejected, but evidence suggests that language does influence certain cognitive processes, such as color perception and spatial reasoning. For minority communities, language is often central to cultural identity and heritage. The loss of a language represents the loss of a unique way of seeing the world. There are currently about 7,000 languages spoken in the world, but many are endangered. Linguists estimate that half of the world''s languages could disappear by the end of this century as smaller languages are displaced by dominant global languages.', 'B2', 'Culture', 5, 178),

('Democracy in the 21st Century', 'Democracy, broadly defined as government by and for the people, is widely considered the most legitimate form of political organization. Yet in recent years, democratic institutions have come under increasing pressure in many parts of the world. Freedom House, which monitors political rights and civil liberties globally, has recorded consecutive years of decline in global democracy. Authoritarian governments have learned to use the mechanisms of democracy — elections, courts, and media — to legitimize their power while hollowing out democratic content. In established democracies, rising inequality, political polarization, and declining trust in institutions pose challenges. Social media has simultaneously empowered citizens and created new vectors for disinformation. Strengthening democracy requires reinvigorating civic engagement, promoting media literacy, and reforming political institutions.', 'B2', 'Politics', 5, 178),

('The Microbiome', 'The human body contains trillions of microorganisms — bacteria, viruses, fungi, and other organisms — collectively known as the microbiome. These microorganisms are not merely passengers but play essential roles in human health. The gut microbiome, the ecosystem of microorganisms in our intestines, influences digestion, immune function, and even mood and behavior through the gut-brain axis. Research has linked disruption of the gut microbiome — a condition called dysbiosis — to a wide range of conditions, including inflammatory bowel disease, obesity, type 2 diabetes, and mental health disorders. Diet is the most important factor shaping the gut microbiome. A diet rich in diverse plant foods promotes microbial diversity. Antibiotics, while essential for treating bacterial infections, can devastate the microbiome and should be used judiciously.', 'B2', 'Science', 5, 178),

('The Psychology of Money', 'Our relationship with money is often irrational and emotionally charged. Morgan Housel, in his influential book, argues that doing well with money has little to do with intelligence and a lot to do with behavior. We are prone to comparing our wealth with others, which drives consumption that outpaces income. We overestimate our future income and underestimate our future expenses, leading to insufficient saving. The hedonic treadmill describes our tendency to adapt rapidly to improvements in our circumstances, so that higher income or possessions do not produce lasting increases in happiness. Research consistently shows that beyond a threshold of comfortable security, additional wealth contributes little to wellbeing. What matters most for financial happiness is freedom — having enough control over your time and choices.', 'B2', 'Psychology', 5, 175),

('Biodiversity and Ecosystem Services', 'Biodiversity — the variety of life on Earth — is not merely aesthetically valuable but provides essential services upon which human civilization depends. Ecosystem services encompass a wide range of benefits: provisioning services such as food, fresh water, and timber; regulating services such as climate regulation, flood control, and water purification; cultural services such as recreation and spiritual value; and supporting services such as soil formation and photosynthesis. The current rate of species extinction is estimated to be 100 to 1,000 times higher than the natural background rate, primarily due to habitat destruction, pollution, climate change, invasive species, and overexploitation. This "sixth mass extinction" threatens the stability of ecosystems and the services they provide. Protecting biodiversity requires both conservation of natural habitats and a fundamental transformation of our economic systems.', 'B2', 'Environment', 5, 178),

('The Philosophy of Free Will', 'The question of whether human beings possess genuine free will is one of the most profound in philosophy. Determinism holds that every event, including every human thought and action, is the inevitable result of prior causes governed by the laws of nature. If determinism is true, it seems that free will is impossible. Compatibilists argue that free will and determinism are not contradictory. On this view, what matters for free will is not whether our actions are caused, but whether they are caused in the right way — by our own desires, values, and deliberation rather than by external compulsion or internal disorder. Hard incompatibilists reject this response and argue that if determinism is true, moral responsibility is impossible. Recent neuroscience adds complexity: studies suggest that brain activity predicting a decision precedes our conscious awareness of deciding.', 'B2', 'Philosophy', 5, 178),

('Global Migration', 'Migration — the movement of people across borders in search of better lives — is one of the defining phenomena of our age. There are currently around 281 million international migrants, representing 3.6% of the world''s population. The factors driving migration are complex and interrelated: economic inequality, political instability, conflict, climate change, and family reunification. Migrants make significant economic contributions to both receiving and sending countries. They fill labor shortages, pay taxes, and often send remittances that support families in their home countries. However, migration also generates political tensions, particularly in receiving countries with native populations concerned about cultural change, job competition, and public services. Designing migration policies that balance economic benefits, humanitarian obligations, and social cohesion is one of the central challenges of contemporary governance.', 'B2', 'Society', 5, 178),

('The Science of Aging', 'Aging is a universal biological process, yet its mechanisms remain incompletely understood. At the cellular level, several hallmarks of aging have been identified. Telomere shortening: each time a cell divides, the protective caps at the ends of chromosomes (telomeres) become shorter. When telomeres become too short, cells can no longer divide. Accumulated DNA damage from radiation, toxins, and metabolic byproducts leads to mutations and cellular dysfunction. The accumulation of damaged proteins and organelles contributes to the deterioration of cellular function. Inflammation, which becomes chronic with age — a phenomenon called "inflammaging" — drives many age-related diseases. Research into interventions that could slow or reverse aspects of aging has intensified. Caloric restriction, metformin, and interventions targeting the senolytic pathway show promise in animal models.', 'B2', 'Science', 5, 178),

-- C1 LEVEL (20 ta)
('The Epistemology of Scientific Knowledge', 'The philosophical question of how science produces knowledge, and what confidence we should have in scientific theories, is more complex than popular conceptions of science suggest. Karl Popper''s falsificationism holds that a scientific theory is distinguished from non-science by its susceptibility to being disproven by evidence. A good scientific theory makes bold, precise predictions that could in principle be false. However, the philosopher W.V.O. Quine pointed out that it is never possible to test a single hypothesis in isolation — any hypothesis is tested in conjunction with auxiliary assumptions. When an experiment appears to falsify a theory, scientists may prefer to revise the auxiliary assumptions rather than the core theory. Thomas Kuhn''s concept of paradigms and scientific revolutions offers a sociological account of how science actually progresses, emphasizing the role of scientific communities and consensus in determining what counts as valid knowledge.', 'C1', 'Philosophy', 6, 198),

('The Neuroscience of Consciousness', 'Consciousness — subjective, first-person experience — remains perhaps the deepest unsolved problem in science and philosophy. The "hard problem of consciousness," formulated by philosopher David Chalmers, asks why and how physical processes in the brain give rise to subjective experience. It seems conceivable that beings physically identical to us could exist without any inner experience — philosophical zombies. If so, physical facts about the brain do not logically entail facts about experience, and no amount of neuroscience will explain why there is something it is like to be conscious. Integrated Information Theory, developed by neuroscientist Giulio Tononi, proposes that consciousness is identical to a specific type of information integration and can in principle be quantified. Global Workspace Theory posits that consciousness arises when information is broadcast widely across the brain, making it available to multiple cognitive processes.', 'C1', 'Science', 6, 198),

('Post-colonial Theory and Literature', 'Post-colonial theory emerged in the latter half of the 20th century as scholars from formerly colonized nations began systematically examining the cultural legacy of European imperialism. Edward Said''s Orientalism, published in 1978, argued that Western scholarship and cultural production had constructed a distorted image of the "Orient" that served to justify colonial domination. Homi Bhabha developed the concept of "hybridity" to describe the complex cultural identities that emerge in colonial and post-colonial contexts, where neither the colonizer''s nor the colonized''s culture remains unaltered. Gayatri Spivak''s influential essay "Can the Subaltern Speak?" questioned whether it is possible for those marginalized by colonial history to represent themselves within discourses shaped by their marginalization. Post-colonial literature, from Chinua Achebe''s Things Fall Apart to Salman Rushdie''s Midnight''s Children, explores these themes through narrative.', 'C1', 'Literature', 6, 198),

('The Political Economy of Inequality', 'The relationship between economic growth and inequality is one of the most contested questions in contemporary political economy. The Kuznets curve hypothesis, influential in the mid-20th century, predicted that inequality would initially rise and then fall as economies developed, suggesting that growth would eventually solve the problem of inequality. This optimistic prediction has not been borne out. Since the 1980s, inequality has risen sharply in most developed countries, driven by technological change, globalization, financialization, declining union power, and deliberate policy choices such as tax cuts and deregulation. Thomas Piketty''s influential analysis argues that when the rate of return on capital exceeds the rate of economic growth — a condition that prevailed throughout most of history — wealth tends to concentrate. Addressing extreme inequality requires a comprehensive set of policies extending well beyond traditional redistribution.', 'C1', 'Economics', 6, 198),

('Theories of Justice', 'Justice is one of the foundational concepts of political philosophy, and different theories yield strikingly different practical conclusions. John Rawls''s theory of justice as fairness, developed in A Theory of Justice, employs the thought experiment of the "veil of ignorance" — choosing principles of justice without knowing one''s place in society. Behind this veil, Rawls argued, rational individuals would choose two principles: equal basic liberties for all, and the "difference principle," permitting social and economic inequalities only insofar as they benefit the least advantaged members of society. Robert Nozick''s libertarian response argued that a minimal state is the only just state, and that any redistribution violates individual rights. Communitarian philosophers such as Michael Sandel challenged Rawls''s "unencumbered self," arguing that our identities are constituted by communities and moral traditions that precede individual choice.', 'C1', 'Philosophy', 6, 198),

('The Complexity of Language Acquisition', 'The question of how children acquire language so rapidly and effortlessly — the so-called "language acquisition problem" — has generated enormous theoretical debate. Noam Chomsky''s nativist theory posited a "language acquisition device," an innate, species-specific cognitive structure containing universal grammatical principles common to all human languages. This "universal grammar" explains why children acquire language without explicit instruction and why all human languages share deep structural similarities. Chomsky''s rivals in the functionalist and usage-based traditions argue that language acquisition can be explained by domain-general learning mechanisms operating on rich linguistic input from caregivers. The debate has been reinvigorated by connectionist models and, more recently, large language models, which demonstrate that extraordinarily complex linguistic behavior can emerge from pattern recognition in large datasets without any built-in grammatical knowledge.', 'C1', 'Linguistics', 6, 198),

('Climate Ethics and Intergenerational Justice', 'Climate change raises profound ethical questions that extend beyond empirical science into moral philosophy. The most fundamental is the question of intergenerational justice: what obligations do present generations owe to those who will inherit the consequences of our emissions, many of whom have not yet been born? Standard cost-benefit analyses apply a discount rate to future costs and benefits, which systematically downvalues the interests of future generations. Critics argue that discounting future people''s welfare is morally unjustifiable. Climate ethics also confronts the problem of collective action: when individual contributions to greenhouse gas emissions are infinitesimally small relative to the global total, how can individual responsibility be established? Furthermore, the unequal distribution of climate change impacts — with the poorest and most vulnerable nations bearing the greatest burdens despite having contributed least to the problem — raises acute questions of distributive justice.', 'C1', 'Ethics', 6, 198),

('The Sociology of Knowledge', 'The sociology of knowledge investigates the social conditions that shape what is considered knowledge in a given society and historical period. Karl Mannheim, one of the founders of the field, argued that ideas and knowledge claims are always embedded in particular social perspectives and interests. The "strong programme" in the sociology of scientific knowledge, associated with David Bloor and Barry Barnes, advanced the provocative claim that the content of scientific knowledge — not merely its acceptance but its very truth — is shaped by social factors. This position has been vigorously contested by philosophers and scientists who maintain that the success of science demonstrates its epistemic autonomy from social forces. More nuanced positions acknowledge the social construction of scientific practices and institutions while maintaining that science has developed reliable methods for producing knowledge that transcends particular social interests.', 'C1', 'Philosophy', 6, 198),

('Narrative Identity', 'The philosopher Paul Ricoeur proposed that human identity is fundamentally narrative in character. We understand ourselves and others through stories — by organizing events into a coherent temporal sequence with a beginning, middle, and end. On this account, personal identity over time is not guaranteed by physical or psychological continuity alone, but requires the construction of a narrative that integrates past experiences, present circumstances, and future projects into a meaningful whole. This narrative self is not static but continually revised in light of new experiences and interpretations. Psychologists have found empirical support for narrative identity theory, demonstrating that the stories people tell about their lives — particularly how they make sense of challenging experiences — predict wellbeing, resilience, and psychological growth. The therapeutic potential of narrative is exploited in narrative therapy and memoir writing.', 'C1', 'Psychology', 6, 198),

('The Limits of Economic Growth', 'The assumption that economic growth is an unqualified good — that more GDP per capita invariably means better human welfare — has been increasingly challenged from multiple directions. Beyond a certain level of material sufficiency, research suggests that additional income produces diminishing returns to subjective wellbeing. The Easterlin paradox notes that while wealthier individuals report higher wellbeing than poorer ones within a given country, countries as a whole do not become happier as they grow richer over time. Environmental economists argue that infinite growth is incompatible with finite planetary resources and the biophysical limits of Earth''s systems. The "doughnut economics" framework, developed by Kate Raworth, proposes that the goal of economics should be to meet the needs of all people within the means of the living planet — a safe and just space for humanity.', 'C1', 'Economics', 6, 198),

('Epigenetics and the Nature-Nurture Debate', 'The discovery of epigenetics has substantially complicated the traditional nature-nurture debate in biology. Classical genetics held that our traits are determined by the DNA sequence we inherit, which is fixed at conception. Epigenetics reveals an additional layer of regulation: chemical modifications to DNA and the proteins around which it is wrapped (histones) that affect gene expression without altering the underlying sequence. Crucially, these epigenetic marks can be influenced by environmental factors such as diet, stress, and social experience. Some epigenetic changes are heritable, transmitted from parents to offspring. This means that the experiences of one generation can influence the biology of subsequent generations — a phenomenon known as transgenerational epigenetic inheritance. These findings challenge the strict separation between genetic and environmental influences on development and behavior.', 'C1', 'Science', 6, 198),

('The Architecture of Power', 'The relationship between spatial organization and social power has been a persistent theme in critical theory. Michel Foucault''s analysis of the panopticon — Jeremy Bentham''s 18th-century prison design in which inmates could be observed at any time without knowing whether they were actually being watched — has become emblematic of modern disciplinary power. Constant potential surveillance induces self-regulation, making external coercion less necessary. Foucault generalized this analysis to hospitals, schools, and factories, arguing that modern institutions exercise power through spatial organization and surveillance. Architecture is never politically neutral. The layout of a city, the design of public spaces, and the architecture of institutions reflect and reproduce social hierarchies. Urban planning has been used to segregate populations, facilitate surveillance, and exclude marginalized groups from public space.', 'C1', 'Philosophy', 6, 198),

('The Global Food System', 'The contemporary global food system, which feeds eight billion people, represents a remarkable technical achievement while simultaneously generating some of the world''s most pressing environmental and social problems. Industrial agriculture has dramatically increased crop yields through mechanization, synthetic fertilizers, pesticides, and the development of high-yielding crop varieties. However, these productivity gains have come at significant ecological cost. Industrial agriculture is responsible for approximately 25% of global greenhouse gas emissions, is the leading driver of biodiversity loss, and has severely degraded soil quality across vast agricultural areas. The food system also generates profound social inequities. Despite producing more than enough food to feed everyone, approximately 820 million people suffer from chronic hunger, while obesity and diet-related diseases claim millions more. Transforming the food system to be ecologically sustainable and socially just is one of the defining challenges of this century.', 'C1', 'Environment', 6, 198),

('Metacognition and Learning', 'Metacognition — thinking about thinking — is increasingly recognized as one of the most important skills for effective learning. It encompasses the ability to monitor one''s own understanding, identify gaps in knowledge, select appropriate learning strategies, and regulate one''s cognitive processes. Research by John Flavell in the 1970s established metacognition as a distinct area of psychological inquiry. Subsequent decades of research have demonstrated that metacognitive skills are strong predictors of academic achievement, independent of general intelligence. Poor learners often overestimate their own understanding — a phenomenon known as the Dunning-Kruger effect — and consequently fail to engage in remedial study. Effective metacognitive strategies include elaborative interrogation (asking why something is true), self-explanation, interleaving different subjects during study, and spaced retrieval practice. Teaching metacognitive strategies explicitly in educational settings significantly improves learning outcomes.', 'C1', 'Education', 6, 198),

('The Anthropocene', 'Geologists have proposed that we have entered a new geological epoch — the Anthropocene — defined by the dominant influence of human activity on Earth''s geology and ecosystems. While the exact start date is debated (candidates include the Agricultural Revolution, the Industrial Revolution, and the post-World War II "Great Acceleration"), there is broad scientific consensus that human activities have fundamentally altered the planet''s systems. The evidence is pervasive: the global spread of radioactive isotopes from nuclear testing, the worldwide presence of microplastics, dramatic increases in reactive nitrogen from synthetic fertilizers, the sixth mass extinction event, and the acceleration of climate change. The concept of the Anthropocene has implications beyond geology. It challenges the boundaries between nature and culture, raises questions about human responsibility for the planet''s future, and forces a reckoning with the consequences of industrial civilization.', 'C1', 'Environment', 6, 198),

('Critical Theory and the Frankfurt School', 'Critical theory, associated with the Frankfurt School of social thought, emerged in Germany in the 1930s as an attempt to develop a theory of society adequate to the conditions of modernity. Max Horkheimer distinguished critical theory from traditional theory by its emancipatory purpose: not merely to understand society but to challenge and change it. Herbert Marcuse''s One-Dimensional Man argued that advanced capitalism had created a "repressive tolerance" in which radical dissent was absorbed and neutralized by the culture industry, producing what he called a one-dimensional society incapable of recognizing its own unfreedom. Theodor Adorno and Max Horkheimer''s Dialectic of Enlightenment argued that the Enlightenment''s project of rational domination of nature had turned against human beings themselves, culminating in the administered society of the 20th century. Jürgen Habermas sought to reconstruct critical theory on the basis of a theory of communicative rationality.', 'C1', 'Philosophy', 6, 198),

('The Political Philosophy of Rights', 'Rights discourse dominates contemporary political and legal thinking, yet the concept of rights is philosophically complex and contested. Natural rights theorists, from John Locke to Robert Nozick, hold that individuals possess rights that are pre-political — that exist independently of and constrain what governments may legitimately do. Jeremy Bentham famously dismissed natural rights as "nonsense upon stilts," arguing that rights are legal constructs that derive their authority from positive law and social utility. The proliferation of human rights claims in the 20th century, embodied in documents like the Universal Declaration of Human Rights, raises questions about the foundations, scope, and enforceability of rights. Should rights be understood as absolute constraints on government action, or as interests that must be weighed against competing considerations? How are conflicts between rights — such as freedom of expression and freedom from discrimination — to be resolved?', 'C1', 'Philosophy', 6, 198),

('Evolutionary Psychology and Its Discontents', 'Evolutionary psychology seeks to understand human behavior by identifying the adaptive problems our ancestors faced in the ancestral environment and the psychological mechanisms that evolved to solve them. Its proponents argue that it provides a principled, scientific foundation for understanding universal human behaviors, including mate preferences, altruism, aggression, and social learning. Critics have raised both empirical and philosophical objections. The "just-so story" objection notes that evolutionary narratives are often constructed post hoc to explain existing data, making them difficult to falsify. The naturalistic fallacy points out that even if a behavior has evolutionary origins, this does not make it morally justified or resistant to change. Feminist critics have argued that evolutionary psychology often inadvertently naturalizes and thereby reinforces existing social inequalities, particularly gender differences. The field continues to generate both productive research and vigorous controversy.', 'C1', 'Psychology', 6, 198),

('The Digital Transformation of Democracy', 'The internet and social media have transformed the conditions of democratic politics in ways whose consequences remain profoundly uncertain. On the optimistic view, digital technologies have lowered the costs of political organizing, enabled new forms of collective action, and given voice to previously marginalized groups. The Arab Spring of 2010-2011 was celebrated as a demonstration of social media''s democratizing potential. More sober assessments have followed. The algorithmic amplification of emotionally resonant, often outrage-inducing content creates filter bubbles and polarizes political discourse. Disinformation — false or misleading information deliberately spread to deceive — has proliferated across digital platforms. State and non-state actors have used social media to manipulate public opinion in other countries. The business models of dominant technology platforms create systematic incentives that appear incompatible with the informational requirements of democratic deliberation.', 'C1', 'Politics', 6, 198),

('The Metaphysics of Personal Identity', 'What makes you the same person you were ten years ago? This question, apparently simple, becomes philosophically bewildering on examination. Physical continuity theories hold that personal identity consists in the continuity of the body or, more specifically, the brain. Psychological continuity theories, associated with John Locke and developed by Derek Parfit, hold that what matters is continuity of memories, intentions, beliefs, and psychological connections. Parfit''s thought experiments — involving brain splitting, teleportation, and gradual replacement — expose tensions in our ordinary concept of personal identity and led him to the radical conclusion that personal identity is not what matters in survival. What matters, he argued, is psychological continuity, which admits of degrees. This conclusion, if accepted, has significant implications for our attitudes to death and our obligations to our future selves.', 'C1', 'Philosophy', 6, 198);

-- =============================================
-- ARTICLE QUESTIONS (har biriga 5 ta savol)
-- =============================================

-- My Daily Routine savollar
WITH art AS (SELECT id FROM articles WHERE title = 'My Daily Routine' LIMIT 1)
INSERT INTO article_questions (article_id, question, option_a, option_b, option_c, option_d, correct_answer, order_num)
SELECT art.id, q.question, q.a, q.b, q.c, q.d, q.correct, q.num FROM art,
(VALUES
  (1, 'What time does the person wake up?', '6 o''clock', '7 o''clock', '8 o''clock', '9 o''clock', 'B'),
  (2, 'What does the person eat for breakfast?', 'Rice and milk', 'Bread, eggs, and tea', 'Cereal and juice', 'Pancakes and coffee', 'B'),
  (3, 'When does school start?', '7 o''clock', '9 o''clock', '8 o''clock', '10 o''clock', 'C'),
  (4, 'What does the person do in the evening?', 'Goes to the gym', 'Watches TV or reads books', 'Meets friends', 'Cooks dinner', 'B'),
  (5, 'What time does the person go to bed?', '9 o''clock', '11 o''clock', '10 o''clock', '12 o''clock', 'C')
) AS q(num, question, a, b, c, d, correct);

-- The History of Pizza savollar
WITH art AS (SELECT id FROM articles WHERE title = 'The History of Pizza' LIMIT 1)
INSERT INTO article_questions (article_id, question, option_a, option_b, option_c, option_d, correct_answer, order_num)
SELECT art.id, q.question, q.a, q.b, q.c, q.d, q.correct, q.num FROM art,
(VALUES
  (1, 'Where did pizza originally come from?', 'France', 'Italy', 'Greece', 'Spain', 'B'),
  (2, 'When did Italian immigrants bring pizza to America?', 'Early 1700s', 'Late 1800s', 'Early 1900s', 'Mid 1900s', 'B'),
  (3, 'When did the first New York pizzeria open?', '1890', '1895', '1905', '1910', 'C'),
  (4, 'What helped make pizza popular in America after WWII?', 'Italian chefs moved to America', 'American soldiers tried pizza in Italy', 'Pizza was cheap to make', 'TV commercials promoted pizza', 'B'),
  (5, 'What are the ingredients of a Margherita pizza?', 'Mushrooms, olives, peppers', 'Meat, onion, garlic', 'Tomato, mozzarella, basil', 'Cheese, bacon, herbs', 'C')
) AS q(num, question, a, b, c, d, correct);

-- The Importance of Sleep savollar
WITH art AS (SELECT id FROM articles WHERE title = 'The Importance of Sleep' LIMIT 1)
INSERT INTO article_questions (article_id, question, option_a, option_b, option_c, option_d, correct_answer, order_num)
SELECT art.id, q.question, q.a, q.b, q.c, q.d, q.correct, q.num FROM art,
(VALUES
  (1, 'What happens to memories during sleep?', 'They are erased', 'They are consolidated', 'They are transferred', 'They are created', 'B'),
  (2, 'How many hours of sleep do adults need per night?', '5-6 hours', '6-7 hours', '7-9 hours', '9-11 hours', 'C'),
  (3, 'Which is NOT mentioned as a risk of chronic sleep deprivation?', 'Obesity', 'Heart disease', 'Blindness', 'Depression', 'C'),
  (4, 'How does poor sleep affect decision-making?', 'It has no effect', 'It improves it', 'It impairs it', 'It speeds it up', 'C'),
  (5, 'What is one recommended strategy for improving sleep?', 'Exercise right before bed', 'Avoid screens before bed', 'Drink coffee in the evening', 'Sleep at different times each night', 'B')
) AS q(num, question, a, b, c, d, correct);
